[package]
name = "vm-download"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
tar.workspace = true
ureq.workspace = true
vm-common.workspace = true

[lints]
workspace = true
